clean: true
author: João Lucas
author_url: https://github.com/heroesofcode
github_url: https://github.com/heroesofcode/ViewState
copyright: Copyright (c) 2020 Anykey Entertrainment. All rights reserved.
xcodebuild_arguments:
   - clean
   - build
   - -project
   - -scheme
   - ViewState-Package
   - -sdk
   - iphonesimulator
output: docs
