disabled_rules:
  
vertical_whitespace:
    severity: error

opt_in_rules:
  - empty_count
  - comma
  
custom_rules:
  final_class:
    included: ".*.swift"
    name: "Final class requirement"
    regex: '^class'
    message: "It's recommended that all classes be final. The only exception are classes that allow inheritance, in these cases, it is 
recommended that this rule be disabled.
."
    severity: warning

excluded:
  - Pods
  - Carthage
  - Fastlane
  - DerivedData
  - Example
  - Tests/ViewStateTests
